# Generated by Django 3.1.7 on 2021-05-03 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210503_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['timeStamp']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='key',
            new_name='userkey',
        ),
    ]
