# Generated by Django 3.1.7 on 2021-05-03 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210503_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='userkey',
            new_name='userid',
        ),
    ]
